import test, { type TestContext } from "node:test";
import assert from "node:assert/strict";
import { createReadStream } from "node:fs";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { auditResources, createResourceDelivery, exportResourceBundle, finishResourceWorkspace, importResourceBundle, materializeResourceTask, preflightResourceInput, preflightResourceTask, receiveResourceDelivery, ResourceStore, selectResources, resourceDescriptorDirectory, sealResourceEvidence, retainResourceResult, type ResourceRoot } from "../src/resources/index.js";
import type { ExecutionEvidenceV1 } from "../src/domain/index.js";
import { FixtureImageProvider, resourceFixture } from "../test-support/resource-fixture.js";
async function temp(t: TestContext) { const root = await mkdtemp(path.join(os.tmpdir(), "hitch-resource-execution-")); t.after(() => rm(root, { recursive: true, force: true })); return root; }
test("overlapping selections retain one CAS closure and isolate task/role writes", async t => {
  const { store, dataset, source, provider } = await resourceFixture(await temp(t));
  const before = await readdir(path.join(store.directory, "objects/sha256"));
  const subsets = [["task-0", "task-1"], ["task-1", "task-2"], ["task-0", "task-2"]];
  provider.calls = 0;
  for (const [index, ids] of subsets.entries()) { const delivery = await createResourceDelivery(store, selectResources(dataset, ids), `experiment:${index}`, 1); assert.ok(JSON.stringify(delivery).length < 18000); }
  assert.equal(provider.calls, subsets.length, "resolve each distinct image once within an admission, then reverify on the next admission");
  assert.deepEqual(await readdir(path.join(store.directory, "objects/sha256")), before);
  const preflight = await preflightResourceInput(store, source, { owner: "execution", generation: 1, platform: "linux/amd64" });
  const plan = preflight!.plans[0]!;
  const first = await materializeResourceTask(store, plan, { owner: "execution:task-0", generation: 1, policy: { mode: "copy" } });
  const second = await materializeResourceTask(store, plan, { owner: "execution:task-0", generation: 1, policy: { mode: "auto" } });
  assert.equal(first.materialized_task_digest, second.materialized_task_digest);
  await writeFile(path.join(first.taskDirectory, "environment/candidate/data/input.txt"), "private mutation");
  assert.match(await readFile(path.join(second.taskDirectory, "environment/candidate/data/input.txt"), "utf8"), /^shared input/);
  await assert.rejects(readFile(path.join(first.taskDirectory, "environment/candidate/answer.txt")), { code: "ENOENT" });
  assert.equal(await readFile(path.join(first.taskDirectory, "tests/answer.txt"), "utf8"), "verifier only");
  await assert.rejects(finishResourceWorkspace(store, first.id, { executionEnded: false, resultSealed: true } as never), /confirmation/);
  await finishResourceWorkspace(store, first.id, { executionEnded: true, resultSealed: true });
  await finishResourceWorkspace(store, second.id, { executionEnded: true, resultSealed: true });
  await store.release("experiment:0:task-0", 1); await store.release("experiment:0:task-1", 1);
  assert.equal((await auditResources(store, { apply: true, graceMs: 0 })).deleted.length, 0);
  await createResourceDelivery(store, selectResources(dataset, ["task-1"]), "experiment:1", 1);
});
test("empty worker receives only missing objects, then verifies the same plan", async t => {
  const directory = await temp(t), { store, dataset } = await resourceFixture(directory);
  const delivery = await createResourceDelivery(store, selectResources(dataset, ["task-0", "task-1"]), "sender", 1);
  const worker = new ResourceStore(path.join(directory, "worker"), { images: new FixtureImageProvider(), limits: { minFreeBytes: 0 } });
  let reads = 0; const reader = async (item: { digest: `sha256:${string}` }) => { reads++; return createReadStream(store.objects.objectPath(item.digest)); };
  const first = await receiveResourceDelivery(worker, delivery, reader, "worker", 1);
  assert.equal(reads, delivery.objects.length); assert.equal(first.missingObjects, reads);
  const second = await receiveResourceDelivery(worker, delivery, reader, "worker", 1);
  assert.equal(second.transferredBytes, 0); assert.equal(reads, delivery.objects.length);
  await assert.rejects(receiveResourceDelivery(new ResourceStore(path.join(directory, "truncated"), { images: new FixtureImageProvider(), limits: { minFreeBytes: 0 } }), delivery, async () => (async function* () { yield Buffer.from("bad"); })(), "bad", 1), /size|truncated|digest/);
});
test("offline bundle deduplicates and requires complete fixed OCI identity before execution", async t => {
  const directory = await temp(t), { store, dataset } = await resourceFixture(directory), bundle = path.join(directory, "bundle");
  const constrained = new ResourceStore(store.root, { images: new FixtureImageProvider(), limits: { minFreeBytes: Number.MAX_SAFE_INTEGER } });
  await assert.rejects(exportResourceBundle(constrained, selectResources(dataset, ["task-0"]), path.join(directory, "too-little-space"), "space-budget"), /free-space/);
  const index = await exportResourceBundle(store, selectResources(dataset, ["task-0", "task-1"]), bundle, "bundle"); assert.equal(index.archives.length, 1);
  const provider = new FixtureImageProvider(); provider.available = false;
  const receiver = new ResourceStore(path.join(directory, "offline"), { images: provider, limits: { minFreeBytes: 0 } });
  const result = await importResourceBundle(receiver, bundle, "offline"); assert.equal(result.selection.tasks.length, 2);
  assert.equal((await importResourceBundle(receiver, bundle, "offline")).transferredBytes, 0);
  await rm(path.join(bundle, "oci", index.archives[0]!.manifestDigest.slice(7)));
  await assert.rejects(importResourceBundle(receiver, bundle, "missing"), /inventory/);
});
test("preflight rejects unknown capabilities, readonly, platform and role leaks before materializing", async t => {
  const { store, dataset, source } = await resourceFixture(await temp(t), 1), task = dataset.tasks[0]!;
  const input = { owner: "bad", generation: 1, platform: "linux/amd64" };
  await assert.rejects(preflightResourceTask(store, { ...task, lock: { ...task.lock, requiredCapabilities: ["quantum@1"] } }, input), /unsupported/);
  await assert.rejects(preflightResourceTask(store, { ...task, lock: { ...task.lock, bindings: task.lock.bindings.map(b => b.use === "input-tree" ? { ...b, access: "read-only" } : b) } }, input), /read-only/);
  await assert.rejects(preflightResourceTask(store, task, { ...input, platform: "linux/arm64" }), /platform/);
  await writeFile(path.join(source, task.task_id, "instruction.md"), "tampered");
  await assert.rejects(preflightResourceInput(store, source, input), /changed/);
  const image = new FixtureImageProvider(); image.available = false;
  await assert.rejects(new ResourceStore(store.root, { images: image }).pin({ owner: "missing-image", generation: 1, purpose: "test", lock: task.lock }), /unavailable/);
});
test("workspace byte/concurrency budgets reject early and leave no writable shared object", async t => {
  const { store, dataset } = await resourceFixture(await temp(t), 1);
  const { plan } = await preflightResourceTask(store, dataset.tasks[0]!, { owner: "budget", generation: 1, platform: "linux/amd64" });
  await assert.rejects(materializeResourceTask(store, plan, { owner: "budget", generation: 1, policy: { mode: "copy", maxCopyBytes: 1 } }), /budget/);
  const w = await materializeResourceTask(store, plan, { owner: "budget", generation: 1, policy: { maxWorkspaces: 1 } });
  await assert.rejects(materializeResourceTask(store, plan, { owner: "budget", generation: 1, policy: { maxWorkspaces: 1 } }), /concurrency/);
  await finishResourceWorkspace(store, w.id, { executionEnded: true, resultSealed: true });
});
test("descriptor views share root protection, quarantine, reacquire and final collection", async t => {
  const { store, dataset } = await resourceFixture(await temp(t), 1), task = dataset.tasks[0]!;
  const view = await resourceDescriptorDirectory(store, task), root = (await store.readRecord<ResourceRoot>("roots", "dataset:task-0"))!;
  await store.release(root.owner, 1);
  await auditResources(store, { apply: true, graceMs: 0 });
  await assert.rejects(readFile(path.join(view, "instruction.md")), { code: "ENOENT" });
  await store.pin({ owner: root.owner, generation: 2, purpose: root.purpose, lock: root.lock });
  assert.equal(await resourceDescriptorDirectory(store, task), view);
  assert.equal(await readFile(path.join(view, "instruction.md"), "utf8"), "task 0");
  await store.release(root.owner, 2);
  await auditResources(store, { apply: true, graceMs: 0 }); await auditResources(store, { apply: true, graceMs: 0 });
  assert.equal((await readdir(path.join(store.directory, "view-quarantine"))).length, 0);
});
test("reimport restores quarantined bytes atomically instead of creating duplicate identities", async t => {
  const directory = await temp(t), store = new ResourceStore(directory, { limits: { minFreeBytes: 0 } }), source = path.join(directory, "input");
  await writeFile(source, "retained content");
  const first = await store.import(source, "blob", "producer"); await store.finishLease(first.leaseId, "ended");
  await auditResources(store, { apply: true, graceMs: 0 });
  const second = await store.import(source, "blob", "retry"); assert.deepEqual(second.resource, first.resource);
  assert.equal((await readdir(path.join(store.directory, "quarantine"))).length, 0);
  assert.equal((await auditResources(store, { apply: true, graceMs: 0 })).deleted.length, 0);
});

test("remote result pins complete materialization at the controller and rejects corrupt or mismatched proof", async t => {
  const directory = await temp(t), { store, dataset } = await resourceFixture(directory, 1), task = dataset.tasks[0]!;
  const delivery = await createResourceDelivery(store, selectResources(dataset, [task.task_id]), "sender", 1);
  const worker = new ResourceStore(path.join(directory, "worker"), { images: new FixtureImageProvider(), limits: { minFreeBytes: 0 } });
  await receiveResourceDelivery(worker, delivery, async item => createReadStream(store.objects.objectPath(item.digest)), "receiver", 1);
  const { plan } = await preflightResourceTask(worker, task, { owner: "trial", generation: 1, platform: "linux/amd64" });
  const workspace = await materializeResourceTask(worker, plan, { owner: "trial", generation: 1, policy: { mode: "copy" } });
  const file = path.join(directory, "resource-evidence.json"), bundle = path.join(directory, "run"), runId = `run_${"1".repeat(32)}`;
  await mkdir(bundle); await writeFile(file, JSON.stringify({ ...workspace, executionEnded: true, preflightPlanDigest: plan.digest }));
  await sealResourceEvidence({ store: worker, file, runDirectory: bundle, owner: `run:${runId}`, taskId: task.task_id, requireObserved: false });
  const evidenceFile = path.join(bundle, "resource.execution.json"), original = await readFile(evidenceFile, "utf8"), evidence = JSON.parse(original);
  const execution = { observed: { containers: [] } } as unknown as ExecutionEvidenceV1;
  const input = { store, directory: bundle, task, runId, execution, requireObserved: false };
  const proof = evidence.proofObjects as Array<{ digest: `sha256:${string}`; size: number }>;
  assert.ok(proof.length > 0); assert.ok(proof.every(p => !delivery.objects.some(i => i.digest === p.digest)));
  const proofFile = path.join(bundle, "resource-proof", proof[0]!.digest.slice(7)), bytes = await readFile(proofFile);
  await writeFile(proofFile, "corruption"); await assert.rejects(retainResourceResult(input), /mismatch/);
  assert.equal(await store.readRecord("roots", `run:${runId}`), undefined);
  await writeFile(proofFile, bytes);
  evidence.images[0].configDigest = `sha256:${"f".repeat(64)}`;
  await writeFile(evidenceFile, JSON.stringify(evidence)); await assert.rejects(retainResourceResult(input), /OCI base differs/);
  await writeFile(evidenceFile, original);
  await assert.rejects(retainResourceResult({ ...input, requireObserved: true }), /observed resource role/);
  await retainResourceResult(input); await retainResourceResult(input);
  const retained = (await store.readRecord<ResourceRoot>("roots", `run:${runId}`))!;
  assert.equal(retained.state, "active");
  await rm(worker.root, { recursive: true });
  for (const digest of retained.closure.objectDigests) await store.objects.verify(digest);
  assert.equal((await auditResources(store, { apply: true, graceMs: 0 })).deleted.length, 0);
});
