export { DEFAULT_MAX_CONCURRENT, DEFAULT_PORT, SCHEMA_VERSION, defaultRoot, hitchRootId, parseDuration, positiveInteger, statePaths } from "./config.js";
export type { StatePaths } from "./config.js";
export { HitchError, invalidInput } from "./errors.js";
export type { HitchErrorOptions } from "./errors.js";
export { appendLine, atomicWriteJSON, ensureDir, readJSON, removeIfExists, writePrivateFile } from "./fs.js";
export { reclaimStaleLock } from "./locks.js";
export { withFileLock } from "./locks.js";
export { captureProcessIdentity, inspectProcessIdentity, validateProcessIdentity } from "./process-identity.js";
export type { ProcessIdentityStatus, ProcessIdentityV1 } from "./process-identity.js";
export type { FileLockOptions } from "./locks.js";
export { beginEvalEnvironmentImagePlanning, readEvalEnvironmentImageReferences, withEnvironmentImageReferenceLock, writeEvalEnvironmentImageReferences } from "./environment-image-references.js";
export type { EvalEnvironmentImageReferencesV1 } from "./environment-image-references.js";
export { consumeLines } from "./line-stream.js";
export { packageRoot, packageVersion } from "./package-root.js";
export { delay, terminateProcess } from "./process.js";
export { commandExecutable, commandVersion, detectVersion, fingerprintExecutable, resolveExecutable, runCommand, selectVersionLine } from "./executable.js";
export type { CommandResult, RunCommandOptions } from "./executable.js";
export { canonicalJSON, digest, sha256Bytes, sha256JSON } from "./hash.js";
export { CREDENTIAL_REDACTION_MARKER, PROVIDER_ENVIRONMENT_NAMES, createCredentialRedactionTransform, credentialValuesFromEnv, redactCredentialText } from "./credential-redaction.js";
export type { CredentialRedactionResult } from "./credential-redaction.js";
